---
- name: install tree
  apt: name=tree state=latest
  become: true

- name: Create subdirectories for the-c-programming-language
  file:
    path: "/home/vagrant/the-c-programming-language/{{ item }}"
    state: directory
  loop:
    - hello-world
    - arrays
    - pointers
    - structures

- name: Create hello.txt
  file:
    path: /home/vagrant/the-c-programming-language/hello-world/hello.txt
    state: touch

- name: Hello World
  lineinfile:
    dest: /home/vagrant/the-c-programming-language/hello-world/hello.txt
    line: "Hello World"
    state: present
    regexp: "Hello World"
