---
- hosts: messi
  remote_user: vagrant
  vars:
    hostname: messi
  tasks:
  - name: install tree
    apt: name=tree state=latest
    become: true

  - name: create user with name similar to hostname
    become: true
    user:
      name: "{{ hostname }}"

  - name: Create subdirectories for the-c-programming-language
    file:
      path: "/home/vagrant/the-c-programming-language/{{ item }}"
      state: directory
    loop:
      - hello-world
      - arrays
      - pointers
      - structures

  - name: Create hello.txt
    file:
      path: /home/vagrant/the-c-programming-language/hello-world/hello.txt
      state: touch

  - name: Hello World
    template:
      src: hello-host.j2
      dest: /home/vagrant/the-c-programming-language/hello-world/hello.txt
